In [49]:
from roboflow import Roboflow
rf = Roboflow(api_key="Bb2wv19Rp5UGNJW71H9j")
project = rf.workspace("danyukezz").project("face_detection-y52o3")
version = project.version(2)
dataset = version.download("yolov8")

loading Roboflow workspace...
loading Roboflow project...
Dependency ultralytics==8.0.196 is required but found version=8.1.34, to fix: `pip install ultralytics==8.0.196`


In [50]:
from ultralytics import YOLO

def main():
    model = YOLO(model="yolov8s.pt")
    model.train(data="/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI model exam/face_recognition/face_detection-2/data.yaml", epochs=5, imgsz=(640, 640), verbose=True, batch=8)
    model.val()
    model.export()

if __name__ == '__main__':
    main()

In [1]:
from roboflow import Roboflow
rf = Roboflow(api_key="Bb2wv19Rp5UGNJW71H9j")
project = rf.workspace("danyukezz").project("ai-emotion-detection-music-bot")
version = project.version(6)
dataset = version.download("folder")

loading Roboflow workspace...
loading Roboflow project...
Exporting format folder in progress : 85.0%
Version export complete for folder format



Extracting Dataset Version Zip to AI-emotion-detection(music-bot)-6 in folder:: 100%|██████████| 18695/18695 [00:04<00:00, 4669.66it/s]


In [36]:
from ultralytics import YOLO
def main():
    model = YOLO(model="/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train9/weights/best.pt")
    model.train(data="/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6", epochs=50, imgsz=(48,48), verbose=True, batch=16)

if __name__ == '__main__':
    main()

Ultralytics YOLOv8.1.34 🚀 Python-3.11.5 torch-2.1.1 CPU (Apple M1)
engine/trainer: task=classify, mode=train, model=/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train9/weights/best.pt, data=/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6, epochs=50, time=None, patience=100, batch=16, imgsz=(48, 48), save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train10, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=

train: Scanning /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/train... 16293 images, 0 corrupt: 100%|██████████| 16293/16293 [00:00<?, ?it/s]
val: Scanning /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/test... 781 images, 0 corrupt: 100%|██████████| 781/781 [00:00<?, ?it/s]

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)


TensorBoard: model graph visualization added ✅
Image sizes 64 train, 64 val
Using 0 dataloader workers
Logging results to runs/classify/train10
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  4.15it/s]

                   all       0.67          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [07:35<00:00, 18.23s/it] 

                   all       0.65          1

      Epoch    GPU_mem       loss  Instances       Size



               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [15:06<00:00, 36.25s/it] 

                   all      0.648          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [15:43<00:00, 37.75s/it]  

                   all      0.643          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:04<00:00,  5.37it/s]

                   all      0.659          1

      Epoch    GPU_mem       loss  Instances       Size



               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.95it/s]

                   all      0.643          1

      Epoch    GPU_mem       loss  Instances       Size



               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:04<00:00,  5.24it/s]

                   all      0.634          1

      Epoch    GPU_mem       loss  Instances       Size



               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:45<00:00,  1.83s/it]

                   all      0.652          1

      Epoch    GPU_mem       loss  Instances       Size



               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:04<00:00,  5.32it/s]

                   all      0.653          1



      Epoch    GPU_mem       loss  Instances       Size


      10/50         0G     0.7366          5         64: 100%|██████████| 1019/1019 [5:02:22<00:00, 17.80s/it]   
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.76it/s]

                   all      0.666          1

      Epoch    GPU_mem       loss  Instances       Size



      11/50         0G     0.7326          5         64: 100%|██████████| 1019/1019 [03:39<00:00,  4.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.87it/s]

                   all      0.645          1

      Epoch    GPU_mem       loss  Instances       Size



      12/50         0G     0.7333          5         64: 100%|██████████| 1019/1019 [04:11<00:00,  4.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.88it/s]

                   all      0.634          1



      Epoch    GPU_mem       loss  Instances       Size


      13/50         0G     0.7212          5         64: 100%|██████████| 1019/1019 [12:06<00:00,  1.40it/s]  
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.65it/s]

                   all      0.643          1



      Epoch    GPU_mem       loss  Instances       Size


      14/50         0G     0.7152          5         64: 100%|██████████| 1019/1019 [04:04<00:00,  4.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  4.06it/s]

                   all      0.644          1

      Epoch    GPU_mem       loss  Instances       Size



      15/50         0G     0.6994          5         64: 100%|██████████| 1019/1019 [03:17<00:00,  5.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.77it/s]

                   all      0.641          1

      Epoch    GPU_mem       loss  Instances       Size



      16/50         0G     0.7013          5         64: 100%|██████████| 1019/1019 [03:19<00:00,  5.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.68it/s]

                   all       0.65          1

      Epoch    GPU_mem       loss  Instances       Size



      17/50         0G     0.7036          5         64: 100%|██████████| 1019/1019 [03:23<00:00,  5.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.57it/s]

                   all      0.624          1

      Epoch    GPU_mem       loss  Instances       Size



      18/50         0G     0.6838          5         64: 100%|██████████| 1019/1019 [03:27<00:00,  4.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.54it/s]

                   all      0.653          1

      Epoch    GPU_mem       loss  Instances       Size



      19/50         0G     0.6861          5         64: 100%|██████████| 1019/1019 [03:25<00:00,  4.96it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.50it/s]

                   all      0.635          1

      Epoch    GPU_mem       loss  Instances       Size



      20/50         0G     0.6694          5         64: 100%|██████████| 1019/1019 [03:26<00:00,  4.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.55it/s]

                   all      0.636          1

      Epoch    GPU_mem       loss  Instances       Size



      21/50         0G     0.6739          5         64: 100%|██████████| 1019/1019 [03:27<00:00,  4.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.52it/s]

                   all       0.65          1

      Epoch    GPU_mem       loss  Instances       Size



      22/50         0G     0.6693          5         64: 100%|██████████| 1019/1019 [03:27<00:00,  4.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.60it/s]

                   all      0.648          1

      Epoch    GPU_mem       loss  Instances       Size



      23/50         0G     0.6613          5         64: 100%|██████████| 1019/1019 [03:28<00:00,  4.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.48it/s]

                   all      0.631          1

      Epoch    GPU_mem       loss  Instances       Size



      24/50         0G     0.6505          5         64: 100%|██████████| 1019/1019 [03:33<00:00,  4.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:07<00:00,  3.19it/s]

                   all      0.635          1



      Epoch    GPU_mem       loss  Instances       Size


      25/50         0G     0.6484          5         64: 100%|██████████| 1019/1019 [14:15<00:00,  1.19it/s]   
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.51it/s]

                   all      0.645          1



      Epoch    GPU_mem       loss  Instances       Size


      26/50         0G     0.6378          5         64: 100%|██████████| 1019/1019 [03:23<00:00,  5.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.59it/s]

                   all      0.627          1

      Epoch    GPU_mem       loss  Instances       Size



      27/50         0G     0.6441          5         64: 100%|██████████| 1019/1019 [03:24<00:00,  4.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.52it/s]

                   all      0.654          1

      Epoch    GPU_mem       loss  Instances       Size



      28/50         0G     0.6631          5         64: 100%|██████████| 1019/1019 [03:36<00:00,  4.71it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.51it/s]

                   all      0.641          1

      Epoch    GPU_mem       loss  Instances       Size



      29/50         0G     0.6497          5         64: 100%|██████████| 1019/1019 [03:28<00:00,  4.89it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.49it/s]

                   all      0.641          1

      Epoch    GPU_mem       loss  Instances       Size



      30/50         0G     0.6443          5         64: 100%|██████████| 1019/1019 [03:51<00:00,  4.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.94it/s]

                   all       0.64          1



      Epoch    GPU_mem       loss  Instances       Size


      31/50         0G     0.6459          5         64: 100%|██████████| 1019/1019 [06:17<00:00,  2.70it/s] 
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.40it/s]

                   all       0.64          1



      Epoch    GPU_mem       loss  Instances       Size


      32/50         0G     0.6226          5         64: 100%|██████████| 1019/1019 [03:58<00:00,  4.28it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.89it/s]

                   all      0.636          1



      Epoch    GPU_mem       loss  Instances       Size


      33/50         0G      0.624          5         64: 100%|██████████| 1019/1019 [03:51<00:00,  4.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.93it/s]

                   all      0.644          1



      Epoch    GPU_mem       loss  Instances       Size


      34/50         0G     0.6088          5         64: 100%|██████████| 1019/1019 [18:22<00:00,  1.08s/it]  
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.71it/s]

                   all      0.631          1

      Epoch    GPU_mem       loss  Instances       Size



      35/50         0G     0.5999          5         64: 100%|██████████| 1019/1019 [03:29<00:00,  4.86it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.58it/s]

                   all      0.644          1

      Epoch    GPU_mem       loss  Instances       Size



      36/50         0G     0.6006          5         64: 100%|██████████| 1019/1019 [03:33<00:00,  4.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:43<00:00,  1.75s/it]

                   all      0.638          1

      Epoch    GPU_mem       loss  Instances       Size



      37/50         0G     0.5942          5         64: 100%|██████████| 1019/1019 [03:23<00:00,  5.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.37it/s]

                   all       0.64          1



      Epoch    GPU_mem       loss  Instances       Size


      38/50         0G     0.5867          5         64: 100%|██████████| 1019/1019 [03:29<00:00,  4.86it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.48it/s]

                   all      0.626          1

      Epoch    GPU_mem       loss  Instances       Size



      39/50         0G     0.5768          5         64: 100%|██████████| 1019/1019 [04:53<00:00,  3.48it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:04<00:00,  5.21it/s]

                   all      0.644          1

      Epoch    GPU_mem       loss  Instances       Size



      40/50         0G     0.5651          5         64: 100%|██████████| 1019/1019 [03:21<00:00,  5.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.55it/s]

                   all      0.635          1

      Epoch    GPU_mem       loss  Instances       Size



      41/50         0G     0.5646          5         64: 100%|██████████| 1019/1019 [03:29<00:00,  4.86it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.50it/s]

                   all      0.636          1

      Epoch    GPU_mem       loss  Instances       Size



      42/50         0G     0.5462          5         64: 100%|██████████| 1019/1019 [03:31<00:00,  4.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.49it/s]

                   all       0.63          1

      Epoch    GPU_mem       loss  Instances       Size



      43/50         0G     0.5381          5         64: 100%|██████████| 1019/1019 [03:31<00:00,  4.82it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.44it/s]

                   all      0.635          1

      Epoch    GPU_mem       loss  Instances       Size



      44/50         0G     0.5386          5         64: 100%|██████████| 1019/1019 [03:32<00:00,  4.79it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.42it/s]

                   all       0.64          1

      Epoch    GPU_mem       loss  Instances       Size



      45/50         0G     0.5227          5         64: 100%|██████████| 1019/1019 [03:39<00:00,  4.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.75it/s]

                   all      0.635          1

      Epoch    GPU_mem       loss  Instances       Size



      46/50         0G      0.509          5         64: 100%|██████████| 1019/1019 [04:22<00:00,  3.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:06<00:00,  3.60it/s]

                   all      0.636          1



      Epoch    GPU_mem       loss  Instances       Size


      47/50         0G     0.5009          5         64: 100%|██████████| 1019/1019 [04:31<00:00,  3.76it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.44it/s]

                   all      0.638          1

      Epoch    GPU_mem       loss  Instances       Size



      48/50         0G     0.4922          5         64: 100%|██████████| 1019/1019 [04:01<00:00,  4.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:07<00:00,  3.41it/s]

                   all      0.639          1



      Epoch    GPU_mem       loss  Instances       Size


      49/50         0G     0.4842          5         64: 100%|██████████| 1019/1019 [04:10<00:00,  4.07it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.33it/s]

                   all      0.643          1

      Epoch    GPU_mem       loss  Instances       Size



      50/50         0G     0.4792          5         64: 100%|██████████| 1019/1019 [03:25<00:00,  4.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.42it/s]

                   all      0.643          1

50 epochs completed in 57.098 hours.
Optimizer stripped from runs/classify/train10/weights/last.pt, 3.0MB


Optimizer stripped from runs/classify/train10/weights/best.pt, 3.0MB

Validating runs/classify/train10/weights/best.pt...
Ultralytics YOLOv8.1.34 🚀 Python-3.11.5 torch-2.1.1 CPU (Apple M1)
YOLOv8n-cls summary (fused): 73 layers, 1440004 parameters, 0 gradients, 3.3 GFLOPs
WARNING ⚠️ Dataset 'split=val' not found, using 'split=test' instead.
train: /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/train... found 16293 images in 4 classes ✅ 
val: None...
test: /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/test... found 781 images in 4 classes ✅ 


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [00:05<00:00,  4.46it/s]


                   all       0.67          1
Speed: 0.0ms preprocess, 3.8ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to runs/classify/train10
Results saved to runs/classify/train10


In [45]:
from ultralytics import YOLO
import albumentations as A
from albumentations.pytorch import ToTensorV2
import cv2

model = YOLO('/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train7/weights/best.pt')

results = model.train(
    data='/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/', 
    epochs=5, 
    imgsz=640
)
transform = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=45, p=0.5),
    A.OneOf([
        A.GaussNoise(),
    ], p=0.2),
    A.OneOf([
        A.MotionBlur(p=0.2),
        A.MedianBlur(blur_limit=3, p=0.1),
        A.Blur(blur_limit=3, p=0.1),
    ], p=0.2),
    A.ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=45, p=0.2),
    A.OneOf([
        A.OpticalDistortion(p=0.3),
        A.GridDistortion(p=0.1),
        A.PiecewiseAffine(p=0.3),
    ], p=0.2),
    A.OneOf([
        A.CLAHE(clip_limit=2),
        A.Sharpen(),
        A.Emboss(),
        A.RandomBrightnessContrast(),
    ], p=0.3),
    A.HueSaturationValue(p=0.3),
    A.Resize(height=640, width=640),
    ToTensorV2()
])

def augment_image(image_path):
    image = cv2.imread(image_path)
    augmented = transform(image=image)
    return augmented['image']

Ultralytics YOLOv8.1.34 🚀 Python-3.11.5 torch-2.1.1 CPU (Apple M1)
engine/trainer: task=classify, mode=train, model=/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train7/weights/best.pt, data=/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/, epochs=5, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train11, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True,

train: Scanning /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/train... 16293 images, 0 corrupt: 100%|██████████| 16293/16293 [00:00<?, ?it/s]
val: Scanning /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/AI-emotion-detection(music-bot)-6/test... 781 images, 0 corrupt: 100%|██████████| 781/781 [00:00<?, ?it/s]

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)


TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs/classify/train11
Starting training for 5 epochs...

      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [02:43<00:00,  6.56s/it]

                   all      0.341          1



      Epoch    GPU_mem       loss  Instances       Size


               classes   top1_acc   top5_acc: 100%|██████████| 25/25 [02:38<00:00,  6.33s/it]

                   all      0.394          1



      Epoch    GPU_mem       loss  Instances       Size


        3/5         0G      1.162         16        640:  65%|██████▌   | 664/1019 [11:15:58<6:01:24, 61.08s/it]      


KeyboardInterrupt: 

In [ ]:
import gradio as gr
from ultralytics import YOLO
from PIL import Image
import numpy as np
import cv2  # Ensure OpenCV is imported

# Load your YOLO models (specify the correct path to your models)
model1 = YOLO('/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/detect/train7/weights/best.pt')
model2 = YOLO('/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train9/weights/best.pt')

def predict(image):
    print(image)
    result = model1.predict(image)

    if not result or len(result[0].boxes) == 0:
        return "No faces detected"

    bounding_box = result[0].boxes[0]  

    x1, y1, x2, y2 = bounding_box.xyxy[0].tolist()

    # Convert the input image to a PIL Image
    original_image = Image.fromarray(image)
    
    cropped_image = original_image.crop((x1, y1, x2, y2))

    # Convert the PIL Image to a NumPy array
    cropped_image_np = np.array(cropped_image)

    # Convert the image from RGB to BGR (if needed)
    cropped_image_np = cv2.cvtColor(cropped_image_np, cv2.COLOR_RGB2BGR)

    # Convert the BGR image to grayscale
    gray_image = cv2.cvtColor(cropped_image_np, cv2.COLOR_BGR2GRAY)

    # Convert the grayscale image back to PIL Image
    gray_image_pil = Image.fromarray(gray_image)
    gray_image_pil.save("cropped_face.jpg")
    
    # Convert the input image to a format YOLO can work with
    results = model2.predict(np.array(gray_image_pil))
    
    # Process and format predictions (e.g., bounding boxes, labels, confidence)
    output = []
    class_labels = ["angry", "happy", "neutral", "sad"]

    # Extract the class probabilities from the predictions
    prediction = results[0]  # Assuming a single prediction
    class_probs = prediction.probs

    # Find the index of the highest confidence score
    top1_index = class_probs.top1
    top1_confidence = class_probs.top1conf

    # Map the index to the corresponding class label
    predicted_emotion = class_labels[top1_index]

    # Print the predicted emotion and its confidence score
    output.append(f"Predicted Emotion: {predicted_emotion}, Confidence Score: {top1_confidence.item():.2f}")

    return "\n".join(output)

iface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="numpy", label="Input Image", sources=["upload", "webcam"]),
    outputs=gr.Textbox(label="Predictions"),
    title="YOLO Model Prediction",
    description="Upload an image to get predictions from the YOLO model"
)

# Launch the Gradio app
iface.launch(share=True)

INFO:httpx:HTTP Request: GET http://127.0.0.1:7883/startup-events "HTTP/1.1 200 OK"


Running on local URL:  http://127.0.0.1:7883


INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.gradio.app/gradio-initiated-analytics/ "HTTP/1.1 200 OK"


IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------


INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7883/ "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://api.gradio.app/v2/tunnel-request "HTTP/1.1 200 OK"



Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.


2024/06/03 16:15:44 [W] [service.go:132] login to server failed: dial tcp 44.237.78.176:7000: i/o timeout


INFO:httpx:HTTP Request: POST https://api.gradio.app/gradio-launched-telemetry/ "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.gradio.app/gradio-error-analytics/ "HTTP/1.1 200 OK"


[[[203 203 195]
  [197 197 189]
  [196 196 188]
  ...
  [175 174 169]
  [187 186 181]
  [183 182 177]]

 [[195 195 187]
  [193 193 185]
  [196 196 188]
  ...
  [175 174 169]
  [180 179 174]
  [172 171 166]]

 [[192 192 184]
  [191 191 183]
  [193 193 185]
  ...
  [182 181 176]
  [186 185 180]
  [182 181 176]]

 ...

 [[167 138 143]
  [159 130 135]
  [158 129 134]
  ...
  [236 215 224]
  [239 218 227]
  [241 220 229]]

 [[164 135 140]
  [163 134 139]
  [162 133 138]
  ...
  [229 208 217]
  [232 211 220]
  [236 215 224]]

 [[162 133 138]
  [164 135 140]
  [165 136 141]
  ...
  [230 209 218]
  [227 206 215]
  [230 209 218]]]

0: 640x480 1 face, 338.1ms
Speed: 10.5ms preprocess, 338.1ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 480)

0: 64x64 happy 0.86, neutral 0.12, sad 0.02, angry 0.00, 13.8ms
Speed: 49.0ms preprocess, 13.8ms inference, 0.3ms postprocess per image at shape (1, 3, 64, 64)
None
WARNING ⚠️ 'source' is missing. Using 'source=/Library/Frameworks/Python.fram

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1684, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/

None
WARNING ⚠️ 'source' is missing. Using 'source=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets'.

image 1/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/bus.jpg: 640x480 1 face, 397.0ms
image 2/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/zidane.jpg: 384x640 (no detections), 581.6ms
Speed: 6.1ms preprocess, 489.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1684, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/

None
WARNING ⚠️ 'source' is missing. Using 'source=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets'.

image 1/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/bus.jpg: 640x480 1 face, 337.8ms
image 2/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/zidane.jpg: 384x640 (no detections), 270.3ms
Speed: 5.2ms preprocess, 304.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1684, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/

In [30]:
import cv2
from ultralytics import YOLO

# Function to take a screenshot from the camera feed
def take_screenshot():
    # Capture a frame from the camera feed
    ret, frame = cap.read()

    if ret:
        # Save the frame as an image
        cv2.imwrite('/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/screenshot.jpg', frame)
    else:
        print("Failed to capture frame from the camera feed")

# Start the camera feed
cap = cv2.VideoCapture(0)  # Change 0 to the appropriate camera index if needed

# Load your trained model
# model = YOLO("/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI model exam/face_recognition/runs/detect/train5/weights/best.pt")

# Listen for key presses
while True:
    # Capture a frame from the camera feed
    ret, frame = cap.read()
    if ret:
        cv2.imshow('Camera Feed', frame)

    key = cv2.waitKey(1) & 0xFF
    if key == ord(' '):  # Space key press
        take_screenshot()
        break
    elif key == ord('q'):  # Q key press
        break

# Close the camera feed and all OpenCV windows
cap.release()
cv2.destroyAllWindows()

In [44]:
import gradio as gr
from ultralytics import YOLO
from PIL import Image
import numpy as np
import cv2  # Ensure OpenCV is imported

# Load your YOLO models (specify the correct path to your models)
model1 = YOLO('/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/detect/train7/weights/best.pt')
model2 = YOLO('/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train9/weights/best.pt')

def predict(image):
    print(image)
    result = model1.predict(image)

    if not result or len(result[0].boxes) == 0:
        return "No faces detected"

    bounding_box = result[0].boxes[0]  

    x1, y1, x2, y2 = bounding_box.xyxy[0].tolist()

    # Convert the input image to a PIL Image
    original_image = Image.fromarray(image)
    
    cropped_image = original_image.crop((x1, y1, x2, y2))

    # Convert the PIL Image to a NumPy array
    cropped_image_np = np.array(cropped_image)

    # Convert the image from RGB to BGR (if needed)
    cropped_image_np = cv2.cvtColor(cropped_image_np, cv2.COLOR_RGB2BGR)

    # Convert the BGR image to grayscale
    gray_image = cv2.cvtColor(cropped_image_np, cv2.COLOR_BGR2GRAY)

    # Convert the grayscale image back to PIL Image
    gray_image_pil = Image.fromarray(gray_image)
    gray_image_pil.save("cropped_face.jpg")
    
    # Convert the input image to a format YOLO can work with
    results = model2.predict(np.array(gray_image_pil))
    
    # Process and format predictions (e.g., bounding boxes, labels, confidence)
    output = []
    class_labels = ["angry", "happy", "neutral", "sad"]

    # Extract the class probabilities from the predictions
    prediction = results[0]  # Assuming a single prediction
    class_probs = prediction.probs

    # Find the index of the highest confidence score
    top1_index = class_probs.top1
    top1_confidence = class_probs.top1conf

    # Map the index to the corresponding class label
    predicted_emotion = class_labels[top1_index]

    # Print the predicted emotion and its confidence score
    output.append(f"Predicted Emotion: {predicted_emotion}, Confidence Score: {top1_confidence.item():.2f}")

    return "\n".join(output)

iface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="numpy", label="Input Image", sources=["upload", "webcam"]),
    outputs=gr.Textbox(label="Predictions"),
    title="YOLO Model Prediction",
    description="Upload an image to get predictions from the YOLO model"
)

# Launch the Gradio app
iface.launch(share=True)

INFO:httpx:HTTP Request: GET http://127.0.0.1:7883/startup-events "HTTP/1.1 200 OK"


Running on local URL:  http://127.0.0.1:7883


INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.gradio.app/gradio-initiated-analytics/ "HTTP/1.1 200 OK"


IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------


INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7883/ "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://api.gradio.app/v2/tunnel-request "HTTP/1.1 200 OK"



Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.


2024/06/03 16:15:44 [W] [service.go:132] login to server failed: dial tcp 44.237.78.176:7000: i/o timeout


INFO:httpx:HTTP Request: POST https://api.gradio.app/gradio-launched-telemetry/ "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.gradio.app/gradio-error-analytics/ "HTTP/1.1 200 OK"


[[[203 203 195]
  [197 197 189]
  [196 196 188]
  ...
  [175 174 169]
  [187 186 181]
  [183 182 177]]

 [[195 195 187]
  [193 193 185]
  [196 196 188]
  ...
  [175 174 169]
  [180 179 174]
  [172 171 166]]

 [[192 192 184]
  [191 191 183]
  [193 193 185]
  ...
  [182 181 176]
  [186 185 180]
  [182 181 176]]

 ...

 [[167 138 143]
  [159 130 135]
  [158 129 134]
  ...
  [236 215 224]
  [239 218 227]
  [241 220 229]]

 [[164 135 140]
  [163 134 139]
  [162 133 138]
  ...
  [229 208 217]
  [232 211 220]
  [236 215 224]]

 [[162 133 138]
  [164 135 140]
  [165 136 141]
  ...
  [230 209 218]
  [227 206 215]
  [230 209 218]]]

0: 640x480 1 face, 338.1ms
Speed: 10.5ms preprocess, 338.1ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 480)

0: 64x64 happy 0.86, neutral 0.12, sad 0.02, angry 0.00, 13.8ms
Speed: 49.0ms preprocess, 13.8ms inference, 0.3ms postprocess per image at shape (1, 3, 64, 64)
None
WARNING ⚠️ 'source' is missing. Using 'source=/Library/Frameworks/Python.fram

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1684, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/

None
WARNING ⚠️ 'source' is missing. Using 'source=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets'.

image 1/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/bus.jpg: 640x480 1 face, 397.0ms
image 2/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/zidane.jpg: 384x640 (no detections), 581.6ms
Speed: 6.1ms preprocess, 489.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1684, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/

None
WARNING ⚠️ 'source' is missing. Using 'source=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets'.

image 1/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/bus.jpg: 640x480 1 face, 337.8ms
image 2/2 /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/assets/zidane.jpg: 384x640 (no detections), 270.3ms
Speed: 5.2ms preprocess, 304.1ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1684, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/

In [31]:
from roboflow import Roboflow
from ultralytics import YOLO
from PIL import Image
from PIL import Image as PILImage
import cv2
import numpy as np

# Initialize Roboflow and download the model
rf = Roboflow(api_key="Bb2wv19Rp5UGNJW71H9j")
project = rf.workspace("danyukezz").project("face_detection-y52o3")
version = project.version(2)
dataset = version.download("yolov8")


model = YOLO("/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/detect/train7/weights/best.pt")


path = "screenshot.jpg"
result = model.predict(path)


bounding_box = result[0].boxes[0]  

x1, y1, x2, y2 = bounding_box.xyxy[0].tolist()

original_image = PILImage.open(path)

cropped_image = original_image.crop((x1, y1, x2, y2))

# cropped_image = cropped_image.resize((48,48), resample=Image.BILINEAR)

# Convert the PIL Image to a NumPy array
cropped_image_np = np.array(cropped_image)

# Convert the image from RGB to BGR (if needed)
cropped_image_np = cv2.cvtColor(cropped_image_np, cv2.COLOR_RGB2BGR)

# Convert the BGR image to grayscale
gray_image = cv2.cvtColor(cropped_image_np, cv2.COLOR_BGR2GRAY)

# Convert the grayscale image back to PIL Image
gray_image_pil = Image.fromarray(gray_image)

# Save the grayscale image
gray_image_pil.save("cropped_face.jpg")

from IPython.display import Image
Image("cropped_face.jpg")

loading Roboflow workspace...
loading Roboflow project...
Dependency ultralytics==8.0.196 is required but found version=8.1.34, to fix: `pip install ultralytics==8.0.196`

image 1/1 /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/screenshot.jpg: 384x640 2 faces, 185.1ms
Speed: 8.0ms preprocess, 185.1ms inference, 14.8ms postprocess per image at shape (1, 3, 384, 640)


In [55]:
# import supervision as sv

# print(model.names)
# def get_keys_from_value(d, val):
#     return [k for k, v in d.items() if v == val]

# detections = sv.Detections.from_ultralytics(result)
# detections = detections[detections.class_id == get_keys_from_value(model.names, 'face')] # if necessary replace by your own class
# print("Amount of faces: ",len(detections))

In [56]:
# import PIL.Image as Image
# import gradio as gr

# from ultralytics import ASSETS

# def predict_image(img, conf_threshold, iou_threshold):
#     results = model.predict(
#         source=img,
#         conf=conf_threshold,
#         iou=iou_threshold,
#         show_labels=True,
#         show_conf=True,
#         imgsz=640,
#         agnostic_nms=True
#     )

#     for r in results:
#         im_array = r.plot()
#         im = Image.fromarray(im_array[..., ::-1])

#     result = model.predict(img)
#     result = result[0] if isinstance(result, list) else result 
#     detections = sv.Detections.from_ultralytics(result)
#     detections = detections[detections.class_id == get_keys_from_value(model.names, 'Drone')]

#     print(results)
#     return im, {len(detections)}


# iface = gr.Interface(
#     fn=predict_image,
#     inputs=[
#         gr.Image(type="pil", label="Upload Image"),
#         gr.Slider(minimum=0, maximum=1, value=0.25, label="Confidence threshold"),
#         gr.Slider(minimum=0, maximum=1, value=0.45, label="IoU threshold")
#     ],
#     outputs=[gr.Image(type="pil", label="Result"), gr.Textbox(label="Amount of drones")],
#     title="Ultralytics Gradio",
#     description="Upload images for inference. The Ultralytics YOLOv8n model is used by default.",
#     theme = gr.themes.Monochrome()

# )

# if __name__ == '__main__':
#     iface.launch()

In [6]:
from roboflow import Roboflow
rf = Roboflow(api_key="Bb2wv19Rp5UGNJW71H9j")
project = rf.workspace().project("ai-emotion-detection-music-bot")
model = project.version(1).model

# infer on a local image
print(model.predict("/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/cropped_face.jpg"))

# visualize your prediction
predictions = model.predict("/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/cropped_face.jpg")
prediction = predictions[0]

# Extract predicted emotions and their confidence scores
predicted_emotions = prediction['predictions']

# Find the emotion with the highest confidence score
max_confidence = 0
predicted_emotion = None

for emotion, info in predicted_emotions.items():
    confidence_score = info['confidence']
    if confidence_score > max_confidence:
        max_confidence = confidence_score
        predicted_emotion = emotion

# Print the predicted emotion with the highest confidence score
print(f"Predicted Emotion with Highest Confidence: {predicted_emotion}, Confidence Score: {max_confidence}")

loading Roboflow workspace...
loading Roboflow project...
{
  "time": 0.12032753700032117,
  "image": {
    "width": 397,
    "height": 275
  },
  "predictions": {
    "angry": {
      "confidence": 0.026481078937649727
    },
    "happy": {
      "confidence": 0.008471661247313023
    },
    "neutral": {
      "confidence": 0.6760207414627075
    },
    "sad": {
      "confidence": 0.38206490874290466
    }
  },
  "predicted_classes": [
    "neutral"
  ],
  "image_path": "/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/cropped_face.jpg",
  "prediction_type": "ClassificationModel"
}


Predicted Emotion with Highest Confidence: neutral, Confidence Score: 0.6760207414627075


In [32]:
from roboflow import Roboflow  # Assuming the YOLO class is in the yolov5 module
import torch
# Initialize Roboflow client
rf = Roboflow(api_key="Bb2wv19Rp5UGNJW71H9j")

# Get project from Roboflow workspace

project = rf.workspace().project("ai-emotion-detection-music-bot")
# model = project.version(1).model

# Define the path to the weights file
weights_path = "/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/runs/classify/train9/weights/best.pt"

# Initialize YOLO model with the weights file
model = YOLO(weights_path)

# Perform inference on the image
predictions = model.predict("/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/cropped_face.jpg")
print(predictions)

class_labels = ["angry", "happy", "neutral", "sad"]

# Extract the class probabilities from the predictions
prediction = predictions[0]  # Assuming a single prediction
class_probs = prediction.probs

# Find the index of the highest confidence score
top1_index = class_probs.top1
top1_confidence = class_probs.top1conf

# Map the index to the corresponding class label
predicted_emotion = class_labels[top1_index]

# Print the predicted emotion and its confidence score
print(f"Predicted Emotion: {predicted_emotion}, Confidence Score: {top1_confidence.item():.2f}")

loading Roboflow workspace...
loading Roboflow project...

image 1/1 /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/cropped_face.jpg: 64x64 happy 0.65, neutral 0.32, sad 0.02, angry 0.01, 7.4ms
Speed: 12.0ms preprocess, 7.4ms inference, 0.1ms postprocess per image at shape (1, 3, 64, 64)
[ultralytics.engine.results.Results object with attributes:

boxes: None
keypoints: None
masks: None
names: {0: 'angry', 1: 'happy', 2: 'neutral', 3: 'sad'}
obb: None
orig_img: array([[[206, 206, 206],
        [207, 207, 207],
        [207, 207, 207],
        ...,
        [210, 210, 210],
        [208, 208, 208],
        [207, 207, 207]],

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [210, 210, 210],
        [208, 208, 208],
        [207, 207, 207]],

       [[212, 212, 212],
        [212, 212, 212],
        [212, 212, 212],
        ...,
        [208, 208, 208],
        [207,

Corrupt JPEG data: premature end of data segment


In [33]:
import csv
import random
import time

# Load the CSV file and store the songs in a dictionary
songs_by_emotion = {1: [], 2: [], 3: [], 4: []}

with open('music.csv', mode='r') as file:
    reader = csv.DictReader(file)
    for row in reader:
        emotion = int(row['Emotion'])
        author = row['Author Name']
        song = row['Song Name']
        songs_by_emotion[emotion].append((author, song))

# Map the predicted emotion to the corresponding emotion code
if predicted_emotion == 'neutral':
    emotion_code = 1
elif predicted_emotion == 'happy':
    emotion_code = 2
elif predicted_emotion == 'sad':
    emotion_code = 3
elif predicted_emotion == 'angry':
    emotion_code = 4

# Get a random song from the list of songs corresponding to the predicted emotion
random_author, random_song = random.choice(songs_by_emotion[emotion_code])
print("Author:", random_author)
print("Song:", random_song)

Author: Justin Timberlake
Song: Can't Stop the Feeling!


In [60]:
# from lcd import LCD

# def get_spaces(spaces):
#       string = ''
#       for i in range(16 - spaces):
#          string += ' '
#       return string

# # Initialize LCD and display the author and the song
# lcd = LCD()
# lcd.lcd_init()
# lcd.send_string(f"{random_author+get_spaces(len(random_author))}", lcd.LCD_LINE_1)
# lcd.send_string(f"{random_song+get_spaces(len(random_song))}", lcd.LCD_LINE_2)
# time.sleep(5)
# lcd.clear()

In [34]:
from pydub import AudioSegment
from pydub.playback import play
import os
import subprocess
import sys

# Directory containing the MP3 files
directory = "/Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/songs"  # Change this to your directory

# Change this to your actual random song variable
print(random_song)

# List all files in the directory
files_in_directory = os.listdir(directory)

# Filter files that contain the song name as a substring
matching_files = [file for file in files_in_directory if random_song.lower() in file.lower()]

# Print the matching files
if matching_files:
    file_path = os.path.join(directory, matching_files[0])
    print(f"Loading file: {file_path}")
    mp3_file = file_path
    
    # Command for ffmpeg to convert MP3 to WAV and output to stdout
    ffmpeg_command = [
        "ffmpeg", 
        "-i", mp3_file, 
        "-f", "wav", 
        "-"
    ]
    
    # Command for ffplay to read WAV audio from stdin
    ffplay_command = [
        "ffplay", 
        "-nodisp",  # Suppress video display
        "-"
    ]
    
    try:
        # Start ffmpeg subprocess to convert MP3 to WAV and output to stdout
        ffmpeg_process = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        
        # Start ffplay subprocess to read WAV audio from stdin
        ffplay_process = subprocess.Popen(ffplay_command, stdin=ffmpeg_process.stdout)
        
        # Wait for the user to exit by pressing Enter
        print("Press Enter to stop playback...")
        input() # Wait for a single character input (Enter key)
        
        # Terminate ffplay process
        ffplay_process.terminate()
        
    except subprocess.CalledProcessError as e:
        print(f"An error occurred: {e}")
else:
    print(f"No matching files found for the song: {random_song}")

Can't Stop the Feeling!
Loading file: /Users/danyukezz/Desktop/1 year 2 semester/project one/2023-2024-projectone-ctai-danyukezz/AI/AI model exam/face_recognition/songs/Justin Timberlake Can't Stop The Feeling! (From Dreamworks Animation's _Trolls_).mp3
Press Enter to stop playback...


ffplay version 7.0.1 Copyright (c) 2003-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex 